### ISSUE TITLE
[QUESTION] pure-javafx solution 

### ISSUE THREAD

**Issue by SirWindfield** [codecentric/NSMenuFX#7]
I am really new to git and github so I might be asking at the wrong place. Sorry if that is actually happening. 
I just wanted to ask why the pure-javafx branch is 4 commits behind the master? Do you just use it as an alternative solution to the swt based library?

Cheers,
Sven

**Comment by 0x4a616e** [comment]
Hi! I recently merged the `pure-javafx` branch back into master, so all changes are on master. Since master had a few additional commits in the meantime, it's now 4 commits ahead. I could as well delete the `pure-javafx` branch now as it is no longer used. So this is also not an alternative to the previous SWT version but a replacement.
